### ISSUE TITLE
Walidacja danych logowania w aplikacji

### ISSUE THREAD

**Issue by bdziurczak** [frajdad/FDNTApp#4]
Wprowadzenie losowego ciągu znaków w jednym z pól w formularzu logowania wywołuje odtwarzanie w nieskończoność tasku logowania. Pomogłaby w tym walidacja danych już na poziomie aplikacji

**Comment by piotrsz1234** [comment]
Dla Email'a wystarczy sprawdzenie jego poprawności:
https://www.techiedelight.com/validate-email-address-java/
Hasło/a to sprawdzenie ich długości
