### ISSUE TITLE
Zmiana layoutu w zakładce Kontakt>Fundacja

### ISSUE THREAD

**Issue by bdziurczak** [frajdad/FDNTApp#6]
Na ekranie Kontakt>Fundacja ikonki względem odpowiadającego im tekstu nie są równo ułożone. Wyglądają jakby były różnej wielkości. Czerwone prostokąty są takiej samej wielkości, a ikony telefonu i maila nie są tak blisko jak ikona trasy.

**Comment by piotrsz1234** [comment]
Tyle, że wszystko jest równo, jak od linijki. Jest to kwestia wielkości ikon, które nie są "równej wielkości" - niektóre mają więcej białego tła po lewej.

**Comment by piotrsz1234** [comment]
Pardon - na górze
